export const hackerNewsActionTypes = {
    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR'
}

export const hackerNewsVoteCountActionTypes = {
    UPDATE_VOTE_COUNT_REQUEST: 'UPDATE_VOTE_COUNT_REQUEST',
    UPDATE_VOTE_COUNT_SUCCESS: 'UPDATE_VOTE_COUNT_SUCCESS',
    UPDATE_VOTE_COUNT_ERROR: 'UPDATE_VOTE_COUNT_ERROR'
}

export const hackerNewsDeleteActionTypes = {
    HACKER_NEWS_DELETE_DATA_REQUEST: 'HACKER_NEWS_DELETE_DATA_REQUEST',
    HACKER_NEWS_DELETE_DATA_SUCCESS: 'HACKER_NEWS_DELETE_DATA_SUCCESS',
    HACKER_NEWS_DELETE_DATA_ERROR: 'HACKER_NEWS_DELETE_DATA_ERROR'
}

export const hackerNewsUpdatePresistTypes = {
    HACKER_NEWS_PERSIST_DATA_REQUEST: 'HACKER_NEWS_PERSIST_DATA_REQUEST',
    HACKER_NEWS_PERSIST_DATA_SUCCESS: 'HACKER_NEWS_PERSIST_DATA_SUCCESS',
    HACKER_NEWS_PERSIST_DATA_ERROR: 'HACKER_NEWS_PERSIST_DATA_ERROR'
}

export const hackerNewsUserActionTypes = {
    FETCH_USER_REQUEST: '@@hackerNewsUser/FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: '@@hackerNewsUser/FETCH_USER_SUCCESS',
    FETCH_USER_ERROR: '@@hackerNewsUser/FETCH_USER_ERROR'
}

export const hackerNewsSearchActionTypes = {
    FETCH_SEARCH_REQUEST: '@@hackerNewsSearch/FETCH_SEARCH_REQUEST',
    FETCH_SEARCH_SUCCESS: '@@hackerNewsSearch/FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_ERROR: '@@hackerNewsSearch/FETCH_SEARCH_ERROR'
}